### ISSUE TITLE
Error during training

### ISSUE THREAD

**Issue by AlessandroTonali** [wizyoung/YOLOv3_TensorFlow#118]
While running train.py i have the following error:
Traceback (most recent call last):
  File "train.py", line 140, in <module>
    feed_dict={is_training: True})
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnknownError: AttributeError: 'NoneType' object has no attribute 'shape'
         [[Node: PyFunc = PyFunc[Tin=[DT_STRING, DT_INT32, DT_INT32, DT_FLOAT, DT_STRING, DT_BOOL, DT_BOOL, DT_BOOL], Tout=[DT_INT64, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], token="pyfunc_0"](arg0, PyFunc/input_1, PyFunc/input_2, PyFunc/input_3, PyFunc/input_4, PyFunc/input_5, PyFunc/input_6, PyFunc/input_7)]]
         [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[<unknown>, <unknown>, <unknown>, <unknown>, <unknown>], output_types=[DT_INT64, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](Iterator)]]
         [[Node: IteratorGetNext/_725 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_150_IteratorGetNext", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

**Comment by wizyoung** [comment]
Your data is not clean. Maybe your image path is not valid. Check it yourself.

**Comment by bujianyiwang** [comment]
I want to use yolov3 to predict the number of real-time person from the rtsp stream with suited interval,anyone has the right python file?
