### ISSUE TITLE
KeyError: 4.0

### ISSUE THREAD

**Issue by smoolya17** [wizyoung/YOLOv3_TensorFlow#125]
`

----------- start to train -----------

       0%|                                                     | 0/9 [00:00<?, ?it/s]2019-08-02 15:25:15.293744: W 

      tensorflow/core/framework/op_kernel.cc:1490] Unknown: KeyError: 4.0
      Traceback (most recent call last):

      File "/home/ml/Downloads/objectv3/lib/python3.7/site-packages/tensorflow/python

      /ops/script_ops.py", line 209, in __call__
      ret = func(*args)

      File "/home/ml/Downloads/YOLOv3_TensorFlow/utils/data_utils.py", line 214, in  

     get_batch_data
     img_idx, img, y_true_13, y_true_26, y_true_52 = parse_data(line, class_num, img_size, 

      anchors,` mode, letterbox_resize)

     File "/home/ml/Downloads/YOLOv3_TensorFlow/utils/data_utils.py", line 174, in parse_data
     y_true_13, y_true_26, y_true_52 = process_box(boxes, labels, img_size, class_num,  
     anchors)

     File "/home/ml/Downloads/YOLOv3_TensorFlow/utils/data_utils.py", line 102, in     
     process_box
    
     ratio = ratio_dict[np.ceil((idx + 1) / 3.)]

      KeyError: 4.0

      2019-08-02 15:25:15.296271: W tensorflow/core/framework/op_kernel.cc:1490] Unknown:                 
      KeyError: 4.0

      Traceback (most recent call last):

      File "/home/ml/Downloads/objectv3/lib/python3.7/site-packages/tensorflow/python
      /ops/script_ops.py", line 209, in __call__
      ret = func(*args)

      File "/home/ml/Downloads/YOLOv3_TensorFlow/utils/data_utils.py", line 214, in 
      get_batch_data
    
      img_idx, img, y_true_13, y_true_26, y_true_52 = parse_data(line, class_num, img_size,  
     anchors, mode, letterbox_resize)  

      File "/home/ml/Downloads/YOLOv3_TensorFlow/utils/data_utils.py", line 174, in parse_data
   
      y_true_13, y_true_26, y_true_52 = process_box(boxes, labels, img_size, class_num, 
      anchors)

      File "/home/ml/Downloads/YOLOv3_TensorFlow/utils/data_utils.py", line 102, in 
      process_box
      ratio = ratio_dict[np.ceil((idx + 1) / 3.)]

      KeyError: 4.0

      @wizyoung @matthew-jack 
       2019-08-02 15:25:15.318995: W tensorflow/core/framework/op_kernel.cc:1490] Unknown:           
      KeyError: 4.0
      Traceback (most recent call last):

      File "/home/ml/Downloads/objectv3/lib/python3.7/site-packages/tensorflow/python
      /ops/script_ops.py", line 209, in __call__
       ret = func(*args)

    File "/home/ml/Downloads/YOLOv3_TensorFlow/utils/data_utils.py", line 214, in  
    get_batch_data
    img_idx, img, y_true_13, y_true_26, y_true_52 = parse_data(line, class_num, img_size, 
     anchors, mode, letterbox_resize)

  
     File "/home/ml/Downloads/YOLOv3_TensorFlow/utils/data_utils.py", line 174, in parse_data
      y_true_13, y_true_26, y_true_52 = process_box(boxes, labels, img_size, class_num, 
      anchors)

     File "/home/ml/Downloads/YOLOv3_TensorFlow/utils/data_utils.py", line 102, in 
     process_box
      ratio = ratio_dict[np.ceil((idx + 1) / 3.)]

       KeyError: 4.0

         2019-08-02 15:25:15.336377: W tensorflow/core/framework/op_kernel.cc:1490]  
       Unknown: KeyError: 4.0

       Traceback (most recent call last):

        File "/home/ml/Downloads/objectv3/lib/python3.7/site-packages/tensorflow/python 
        /ops/script_ops.py", line 209, in __call__
    
        ret = func(*args)

  
       File "/home/ml/Downloads/YOLOv3_TensorFlow/utils/data_utils.py", line 214, in 
       get_batch_data
       img_idx, img, y_true_13, y_true_26, y_true_52 = parse_data(line, class_num, img_size, 
       anchors, mode, letterbox_resize)

  
       File "/home/ml/Downloads/YOLOv3_TensorFlow/utils/data_utils.py", line 174, in parse_data
    
       y_true_13, y_true_26, y_true_52 = process_box(boxes, labels, img_size, class_num, 
       anchors)

        File "/home/ml/Downloads/YOLOv3_TensorFlow/utils/data_utils.py", line 102, in 
        process_box
    
        ratio = ratio_dict[np.ceil((idx + 1) / 3.)]

         KeyError: 4.0

         2019-08-02 15:25:15.346559: W tensorflow/core/framework/op_kernel.cc:1490] 
         Unknown: KeyError: 4.0
         Traceback (most recent call last):

        File "/home/ml/Downloads/objectv3/lib/python3.7/site-packages/tensorflow/python
        /ops/script_ops.py", line 209, in __call__
    
        ret = func(*args)

  
      File "/home/ml/Downloads/YOLOv3_TensorFlow/utils/data_utils.py", line 214, in 
      get_batch_data
    
       img_idx, img, y_true_13, y_true_26, y_true_52 = parse_data(line, class_num, img_size, 
       anchors, mode, letterbox_resize)

       File "/home/ml/Downloads/YOLOv3_TensorFlow/utils/data_utils.py", line 174, in parse_data
       y_true_13, y_true_26, y_true_52 = process_box(boxes, labels, img_size, class_num,    

      anchors)

      File "/home/ml/Downloads/YOLOv3_TensorFlow/utils/data_utils.py", line 102, in 
      process_box
     ratio = ratio_dict[np.ceil((idx + 1) / 3.)]

      KeyError: 4.0

    2019-08-02 15:25:15.369989: W tensorflow/core/framework/op_kernel.cc:1490] Unknown:   
    KeyError: 4.0
    Traceback (most recent call last):

     File "/home/ml/Downloads/objectv3/lib/python3.7/site-packages/tensorflow/python
     /ops/script_ops.py", line 209, in __call__
     ret = func(*args)

     File "/home/ml/Downloads/YOLOv3_TensorFlow/utils/data_utils.py", line 214, in 
     get_batch_data
     img_idx, img, y_true_13, y_true_26, y_true_52 = parse_data(line, class_num, img_size, 
     anchors, mode, letterbox_resize)

      File "/home/ml/Downloads/YOLOv3_TensorFlow/utils/data_utils.py", line 174, in parse_data
      y_true_13, y_true_26, y_true_52 = process_box(boxes, labels, img_size, class_num, 
      anchors)

      File "/home/ml/Downloads/YOLOv3_TensorFlow/utils/data_utils.py", line 102, in 
      process_box
      ratio = ratio_dict[np.ceil((idx + 1) / 3.)]

      KeyError: 4.0

          2019-08-02 15:25:15.399923: W tensorflow/core/framework/op_kernel.cc:1490]                             
         Unknown: KeyError: 4.0

         Traceback (most recent call last):

  
         File "/home/ml/Downloads/objectv3/lib/python3.7/site-packages/tensorflow/python  
         /ops/script_ops.py", line 209, in __call__
    
        ret = func(*args)

       File "/home/ml/Downloads/YOLOv3_TensorFlow/utils/data_utils.py", line 214, in   
       get_batch_data
       img_idx, img, y_true_13, y_true_26, y_true_52 = parse_data(line, class_num, img_size, 
       anchors, mode, letterbox_resize)

      File "/home/ml/Downloads/YOLOv3_TensorFlow/utils/data_utils.py", line 174, in parse_data
    
      y_true_13, y_true_26, y_true_52 = process_box(boxes, labels, img_size, class_num, 
    
    anchors)

      File "/home/ml/Downloads/YOLOv3_TensorFlow/utils/data_utils.py", line 102, in 
     process_box
      ratio = ratio_dict[np.ceil((idx + 1) / 3.)]

      KeyError: 4.0

**Comment by smoolya17** [comment]
The key-error is due to incorrect anchor number generated.
Default set to 9 when changed to 12 gave me this error.

**Comment by AnikaP** [comment]
Have you solved this @smoolya17 ? I would like to try using more anchors and ran into this error.

**Comment by smoolya17** [comment]
@AnikaP I fear increasing the anchor size increases the processing time if not the mAP is low or you have a GPU to try out.

I did not try to change the anchor number.

But you may try once but also make sure to insert the 12 anchor values generated using `k-means.py`

**Comment by smoolya17** [comment]
@AnikaP the issue is due to incorrect number of anchor numbers set in `args.py` & `train.py`

**Comment by smoolya17** [comment]
the anchor results must match the above numbers
