### ISSUE TITLE
Unknown: AssertionError: Annotation error!

### ISSUE THREAD

**Issue by smoolya17** [wizyoung/YOLOv3_TensorFlow#127]
I have successfully implemented the train.py file.

When I run the eval.py code I face the below error:

my test file looks like this:

```
0 /home/ml/Downloads/YOLOv3_TensorFlow/data/my_data/Bank_Proof/test/TE922428_Bank_Proof~2
1 /home/ml/Downloads/YOLOv3_TensorFlow/data/my_data/Bank_Proof/test/TE922453_Bank_Proof~2
2 /home/ml/Downloads/YOLOv3_TensorFlow/data/my_data/Bank_Proof/test/TE922492_Bank_Proof~2
3 /home/ml/Downloads/YOLOv3_TensorFlow/data/my_data/Bank_Proof/test/TE922493_Bank_Proof~2
4 /home/ml/Downloads/YOLOv3_TensorFlow/data/my_data/Bank_Proof/test/TE922501_Bank_Proof~2
5 /home/ml/Downloads/YOLOv3_TensorFlow/data/my_data/Bank_Proof/test/TE922564_Bank_Proof_1~2
6 /home/ml/Downloads/YOLOv3_TensorFlow/data/my_data/Bank_Proof/test/TE922646_Bank_Proof~2
7 /home/ml/Downloads/YOLOv3_TensorFlow/data/my_data/Bank_Proof/test/TE922702_Bank_Proof~2
8 /home/ml/Downloads/YOLOv3_TensorFlow/data/my_data/Bank_Proof/test/TE922786_Bank_Proof~2
```

And the error code like this:

```
----------- start to eval -----------

  0%|          | 0/9 [00:00<?, ?it/s]2019-08-05 15:07:58.242949: W tensorflow/core/framework/op_kernel.cc:1490] Unknown: AssertionError: Annotation error! Please check your annotation file. Make sure there is at least one target object in each image.
Traceback (most recent call last):

  File "/home/ml/Downloads/objectv3/lib/python3.7/site-packages/tensorflow/python/ops/script_ops.py", line 209, in __call__
    ret = func(*args)

  File "/home/ml/Downloads/YOLOv3_TensorFlow/utils/data_utils.py", line 214, in get_batch_data
    img_idx, img, y_true_13, y_true_26, y_true_52 = parse_data(line, class_num, img_size, anchors, mode, letterbox_resize)

  File "/home/ml/Downloads/YOLOv3_TensorFlow/utils/data_utils.py", line 129, in parse_data
    img_idx, pic_path, boxes, labels, _, _ = parse_line(line)

  File "/home/ml/Downloads/YOLOv3_TensorFlow/utils/data_utils.py", line 31, in parse_line
    assert len(s) > 8, 'Annotation error! Please check your annotation file. Make sure there is at least one target object in each image.'

AssertionError: Annotation error! Please check your annotation file. Make sure there is at least one target object in each image.
```

What change is needed in the test.txt document?

**Comment by smoolya17** [comment]
I assumed eval.py as the test code(testing to be done on new image) although which in this case it is the validation code to calculate the metrics of trained model, which are different in each case.
