### ISSUE TITLE
train問題

### ISSUE THREAD

**Issue by aluds123** [wizyoung/YOLOv3_TensorFlow#150]
您好:
       想請教個問題，在訓練時碰到這個問題:
2019-09-09 15:42:23.284673: W tensorflow/core/common_runtime/bfc_allocator.cc:211] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.14GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
所以我嘗試將batch size 改小，但又變成其他的問題:
2019-09-09 16:11:32.790987: W tensorflow/core/framework/op_kernel.cc:1261] Invalid argument: exceptions.ValueError: sample larger than population
Traceback (most recent call last):

  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/script_ops.py", line 206, in __call__
    ret = func(*args)

  File "/home/soc507/YOLOv3_TensorFlow-master_test/utils/data_utils.py", line 208, in get_batch_data
    mix_lines.append([line, random.sample(batch_line[:idx] + batch_line[idx+1:], 1)[0]])

  File "/usr/lib/python2.7/random.py", line 323, in sample
    raise ValueError("sample larger than population")

ValueError: sample larger than population
############
想請問有甚麼建議嗎?

**Comment by pgirikishore** [comment]
How did you solve the issue?

**Comment by aluds123** [comment]
I forgot what I do. But if u have some questions, I'll try my best to help u.
