### ISSUE TITLE
IndexError: index 57 is out of bounds for axis 1 with size 52 

### ISSUE THREAD

**Issue by aluds123** [wizyoung/YOLOv3_TensorFlow#189]
@wizyoung @matthew-jack 
Hi, I have a trouble with my dataset. I have a dataset with yolo label type, so I write a .py to change my dataset to the wizyoung's type. I have try about 8000 images to train on this project, and it can work. 
But when I add my dataset to 25000 images and train it, it shows "IndexError: index 57 is out of bounds for axis 1 with size 52". (maybe something wrong with my data?)
Can you give me some advices?

----------------------------------------------------------------------------------------------------

2019-12-09 22:40:27.325195: W tensorflow/core/framework/op_kernel.cc:1490] Unknown: IndexError: index 57 is out of bounds for axis 1 with size 52
Traceback (most recent call last):

  File "/home/aluds/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/script_ops.py", line 209, in __call__
    ret = func(*args)

  File "/home/aluds/dachi_quant/utils/data_utils.py", line 214, in get_batch_data
    img_idx, img, y_true_13, y_true_26, y_true_52 = parse_data(line, class_num, img_size, anchors, mode, letterbox_resize)

  File "/home/aluds/dachi_quant/utils/data_utils.py", line 174, in parse_data
    y_true_13, y_true_26, y_true_52 = process_box(boxes, labels, img_size, class_num, anchors)

  File "/home/aluds/dachi_quant/utils/data_utils.py", line 109, in process_box
    y_true[feature_map_group][y, x, k, :2] = box_centers[i]

IndexError: index 57 is out of bounds for axis 1 with size 52

 29%|███████████████████████████████████████████████▉                                                                                                                       | 2125/7410 [02:08<05:29, 16.06it/s]Traceback (most recent call last):
  File "/home/aluds/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/home/aluds/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/aluds/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.UnknownError: IndexError: index 57 is out of bounds for axis 1 with size 52
Traceback (most recent call last):

  File "/home/aluds/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/script_ops.py", line 209, in __call__
    ret = func(*args)

  File "/home/aluds/dachi_quant/utils/data_utils.py", line 214, in get_batch_data
    img_idx, img, y_true_13, y_true_26, y_true_52 = parse_data(line, class_num, img_size, anchors, mode, letterbox_resize)

  File "/home/aluds/dachi_quant/utils/data_utils.py", line 174, in parse_data
    y_true_13, y_true_26, y_true_52 = process_box(boxes, labels, img_size, class_num, anchors)

  File "/home/aluds/dachi_quant/utils/data_utils.py", line 109, in process_box
    y_true[feature_map_group][y, x, k, :2] = box_centers[i]

IndexError: index 57 is out of bounds for axis 1 with size 52

         [[{{node PyFunc}}]]
         [[IteratorGetNext]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 198, in <module>
    feed_dict={is_training: False})
  File "/home/aluds/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/home/aluds/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/aluds/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/home/aluds/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnknownError: IndexError: index 57 is out of bounds for axis 1 with size 52
Traceback (most recent call last):

  File "/home/aluds/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/script_ops.py", line 209, in __call__
    ret = func(*args)

  File "/home/aluds/dachi_quant/utils/data_utils.py", line 214, in get_batch_data
    img_idx, img, y_true_13, y_true_26, y_true_52 = parse_data(line, class_num, img_size, anchors, mode, letterbox_resize)

  File "/home/aluds/dachi_quant/utils/data_utils.py", line 174, in parse_data
    y_true_13, y_true_26, y_true_52 = process_box(boxes, labels, img_size, class_num, anchors)

  File "/home/aluds/dachi_quant/utils/data_utils.py", line 109, in process_box
    y_true[feature_map_group][y, x, k, :2] = box_centers[i]

IndexError: index 57 is out of bounds for axis 1 with size 52

         [[{{node PyFunc}}]]
         [[IteratorGetNext]]

--------------------------------------------------------------------------------------------------------

**Comment by manuelseisl** [comment]
I have the same problem. Can you give me some advices?
