### ISSUE TITLE
当我运行时遇到了如下报错，请给点提示。

### ISSUE THREAD

**Issue by BlackAcer09** [wizyoung/YOLOv3_TensorFlow#2]
Traceback (most recent call last):
  File "test_single_image.py", line 52, in <module>
    saver.restore(sess, args.restore_path)
  File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\training\saver.py", line 1538, in restore
    + compat.as_text(save_path))
ValueError: The passed save_path is not a valid checkpoint: ./data/darknet_weights/yolov3.ckpt

**Comment by wizyoung** [comment]
你需要下载 TensorFlow 的权重，并把三个文件解压后放在 ./data/darknet_weights/ 文件夹下
