### ISSUE TITLE
a problem about type of txt

### ISSUE THREAD

**Issue by xiaos16** [wizyoung/YOLOv3_TensorFlow#20]
2019-03-06 22:22:51.632340: W T:\src\github\tensorflow\tensorflow\core\framework\op_kernel.cc:1306] Invalid argument: TypeError: a bytes-like object is required, not 'str'
Traceback (most recent call last):

  File "C:\Users\Xiaos\Anaconda3\lib\site-packages\tensorflow\python\ops\script_ops.py", line 158, in __call__
    ret = func(*args)

  File "F:\DL\YOLOv3_TensorFlow\utils\data_utils.py", line 130, in parse_data
    pic_path, boxes, labels = parse_line(line)

  File "F:\DL\YOLOv3_TensorFlow\utils\data_utils.py", line 19, in parse_line
    s = line.strip().split(' ')

TypeError: a bytes-like object is required, not 'str'

what does the error mean?  could someone tell me how to construt the train.txt? I use the coco dataset, the txt file is the following
F:/PascalVOCdataset/VOCdevkit/VOC2007/JPEGImages/003949.jpg 11 210 151 245 193

any people know where is the error?

**Comment by dzyjjpy** [comment]
s = line.strip().split(' ')
replace:  s = line.decode().strip().split(' ')
to have a try.

**Comment by xiaos16** [comment]
@dzyjjpy  thanks! It works!

**Comment by dzyjjpy** [comment]
u r welcome @xiaos16
