### ISSUE TITLE
出现这个错误

### ISSUE THREAD

**Issue by eain3314** [wizyoung/YOLOv3_TensorFlow#50]
tensorflow.python.framework.errors_impl.InvalidArgumentError: 0-th value returned by pyfunc_0 is int32, but expects int64
出现这个错误怎么办啊 大佬

**Comment by wizyoung** [comment]
提问前先搜索一下issues
试试 [#48](https://github.com/wizyoung/YOLOv3_TensorFlow/issues/48)

**Comment by eain3314** [comment]
----------- start to train -----------

  0%|          | 0/154 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "D:\anacconda\lib\site-packages\tensorflow\python\client\session.py", line 1278, in _do_call
    return fn(*args)
  File "D:\anacconda\lib\site-packages\tensorflow\python\client\session.py", line 1263, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "D:\anacconda\lib\site-packages\tensorflow\python\client\session.py", line 1350, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 0-th value returned by pyfunc_0 is int32, but expects int64
	 [[Node: PyFunc = PyFunc[Tin=[DT_STRING, DT_INT32, DT_INT32, DT_FLOAT, DT_STRING, DT_BOOL, DT_BOOL], Tout=[DT_INT64, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], token="pyfunc_0"](arg0, PyFunc/input_1, PyFunc/input_2, PyFunc/input_3, PyFunc/input_4, PyFunc/input_5, PyFunc/input_5)]]
	 [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[<unknown>, <unknown>, <unknown>, <unknown>, <unknown>], output_types=[DT_INT64, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](Iterator)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:/net/new/YOLOv3_TensorFlow-master/train.py", line 134, in <module>
    feed_dict={is_training: True})
  File "D:\anacconda\lib\site-packages\tensorflow\python\client\session.py", line 877, in run
    run_metadata_ptr)
  File "D:\anacconda\lib\site-packages\tensorflow\python\client\session.py", line 1100, in _run
    feed_dict_tensor, options, run_metadata)
  File "D:\anacconda\lib\site-packages\tensorflow\python\client\session.py", line 1272, in _do_run
    run_metadata)
  File "D:\anacconda\lib\site-packages\tensorflow\python\client\session.py", line 1291, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 0-th value returned by pyfunc_0 is int32, but expects int64
	 [[Node: PyFunc = PyFunc[Tin=[DT_STRING, DT_INT32, DT_INT32, DT_FLOAT, DT_STRING, DT_BOOL, DT_BOOL], Tout=[DT_INT64, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], token="pyfunc_0"](arg0, PyFunc/input_1, PyFunc/input_2, PyFunc/input_3, PyFunc/input_4, PyFunc/input_5, PyFunc/input_5)]]
	 [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[<unknown>, <unknown>, <unknown>, <unknown>, <unknown>], output_types=[DT_INT64, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](Iterator)]]

Process finished with exit code 1

**Comment by eain3314** [comment]
> 提问前先搜索一下问题
> 试试[＃48](https://github.com/wizyoung/YOLOv3_TensorFlow/issues/48)

**Comment by lovepan1** [comment]
i also meet the this error.
the error log :
Traceback (most recent call last):
  File "/home/pcl/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 158, in __call__
    ret = func(*args)
  File "/home/pcl/tensorflow1.12/YOLOv3_TensorFlow/utils/data_utils.py", line 205, in get_batch_data
    img_idx, img, y_true_13, y_true_26, y_true_52 = parse_data(line, class_num, img_size, anchors, mode)
  File "/home/pcl/tensorflow1.12/YOLOv3_TensorFlow/utils/data_utils.py", line 124, in parse_data
    boxes = np.concatenate((boxes, np.full(shape=(boxes.shape[0], 1), fill_value=1., dtype=np.float32)), axis=-1)

ValueError: all the input arrays must have same number of dimensions
         [[Node: PyFunc = PyFunc[Tin=[DT_STRING, DT_INT32, DT_INT32, DT_FLOAT, DT_STRING, DT_BOOL, DT_BOOL], Tout=[DT_INT64, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], token="pyfunc_0"](arg0, PyFunc/input_1, PyFunc/input_2, PyFunc/input_3, PyFunc/input_4, PyFunc/input_5, PyFunc/input_5)]]
         [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[<unknown>, <unknown>, <unknown>, <unknown>, <unknown>], output_types=[DT_INT64, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](Iterator)]]

#48   cannot solve my problem 
could you give me some advice? thank you
