### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by eain3314** [wizyoung/YOLOv3_TensorFlow#58]
Traceback (most recent call last):

  File "D:\anacconda\lib\site-packages\tensorflow\python\ops\script_ops.py", line 206, in __call__
    ret = func(*args)

  File "E:\net\new\YOLOv3_TensorFlow-master\utils\data_utils.py", line 205, in get_batch_data
    img_idx, img, y_true_13, y_true_26, y_true_52 = parse_data(line, class_num, img_size, anchors, mode)

  File "E:\net\new\YOLOv3_TensorFlow-master\utils\data_utils.py", line 124, in parse_data
    boxes = np.concatenate((boxes, np.full(shape=(boxes.shape[0], 1), fill_value=1., dtype=np.float32)), axis=-1)

ValueError: all the input arrays must have same number of dimensions

 55%|█████▌    | 1193/2150 [03:18<02:28,  6.45it/s]Traceback (most recent call last):
  File "D:\anacconda\lib\site-packages\tensorflow\python\client\session.py", line 1278, in _do_call
    return fn(*args)
  File "D:\anacconda\lib\site-packages\tensorflow\python\client\session.py", line 1263, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "D:\anacconda\lib\site-packages\tensorflow\python\client\session.py", line 1350, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: ValueError: all the input arrays must have same number of dimensions
Traceback (most recent call last):

  File "D:\anacconda\lib\site-packages\tensorflow\python\ops\script_ops.py", line 206, in __call__
    ret = func(*args)

  File "E:\net\new\YOLOv3_TensorFlow-master\utils\data_utils.py", line 205, in get_batch_data
    img_idx, img, y_true_13, y_true_26, y_true_52 = parse_data(line, class_num, img_size, anchors, mode)

  File "E:\net\new\YOLOv3_TensorFlow-master\utils\data_utils.py", line 124, in parse_data
    boxes = np.concatenate((boxes, np.full(shape=(boxes.shape[0], 1), fill_value=1., dtype=np.float32)), axis=-1)

ValueError: all the input arrays must have same number of dimensions

	 [[Node: PyFunc = PyFunc[Tin=[DT_STRING, DT_INT32, DT_INT32, DT_FLOAT, DT_STRING, DT_BOOL, DT_BOOL], Tout=[DT_INT64, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], token="pyfunc_0"](arg0, PyFunc/input_1, PyFunc/input_2, PyFunc/input_3, PyFunc/input_4, PyFunc/input_5, PyFunc/input_5)]]
	 [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[<unknown>, <unknown>, <unknown>, <unknown>, <unknown>], output_types=[DT_INT64, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](Iterator)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:/net/new/YOLOv3_TensorFlow-master/train.py", line 134, in <module>
    feed_dict={is_training: True})
  File "D:\anacconda\lib\site-packages\tensorflow\python\client\session.py", line 877, in run
    run_metadata_ptr)
  File "D:\anacconda\lib\site-packages\tensorflow\python\client\session.py", line 1100, in _run
    feed_dict_tensor, options, run_metadata)
  File "D:\anacconda\lib\site-packages\tensorflow\python\client\session.py", line 1272, in _do_run
    run_metadata)
  File "D:\anacconda\lib\site-packages\tensorflow\python\client\session.py", line 1291, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: ValueError: all the input arrays must have same number of dimensions
Traceback (most recent call last):

  File "D:\anacconda\lib\site-packages\tensorflow\python\ops\script_ops.py", line 206, in __call__
    ret = func(*args)

  File "E:\net\new\YOLOv3_TensorFlow-master\utils\data_utils.py", line 205, in get_batch_data
    img_idx, img, y_true_13, y_true_26, y_true_52 = parse_data(line, class_num, img_size, anchors, mode)

  File "E:\net\new\YOLOv3_TensorFlow-master\utils\data_utils.py", line 124, in parse_data
    boxes = np.concatenate((boxes, np.full(shape=(boxes.shape[0], 1), fill_value=1., dtype=np.float32)), axis=-1)

ValueError: all the input arrays must have same number of dimensions

	 [[Node: PyFunc = PyFunc[Tin=[DT_STRING, DT_INT32, DT_INT32, DT_FLOAT, DT_STRING, DT_BOOL, DT_BOOL], Tout=[DT_INT64, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], token="pyfunc_0"](arg0, PyFunc/input_1, PyFunc/input_2, PyFunc/input_3, PyFunc/input_4, PyFunc/input_5, PyFunc/input_5)]]
	 [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[<unknown>, <unknown>, <unknown>, <unknown>, <unknown>], output_types=[DT_INT64, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](Iterator)]]

Process finished with exit code 1

**Comment by eain3314** [comment]
why?

**Comment by eain3314** [comment]
请问一下，为什么会出现这个问题?数据集没问题啊

**Comment by wizyoung** [comment]
你在data_utils.py 124 行前面加一个 print(boxes.shape)，看报错的时候这个shape是多少

**Comment by eain3314** [comment]
![image](https://user-images.githubusercontent.com/48511773/57744000-fc19e300-76f9-11e9-9f9f-6870922de672.png)

**Comment by eain3314** [comment]
42%|████▏     | 903/2150 [02:34<03:19,  6.24it/s](71, 5)
(7, 5)
 42%|████▏     | 904/2150 [02:34<03:19,  6.25it/s](14, 5)
(8, 5)
 42%|████▏     | 905/2150 [02:34<03:18,  6.27it/s]Traceback (most recent call last):
  File "D:\anacconda\lib\site-packages\tensorflow\python\client\session.py", line 1278, in _do_call
    return fn(*args)
  File "D:\anacconda\lib\site-packages\tensorflow\python\client\session.py", line 1263, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "D:\anacconda\lib\site-packages\tensorflow\python\client\session.py", line 1350, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: ValueError: all the input arrays must have same number of dimensions
Traceback (most recent call last):

  File "D:\anacconda\lib\site-packages\tensorflow\python\ops\script_ops.py", line 206, in __call__
    ret = func(*args)

  File "E:\net\new\YOLOv3_TensorFlow-master\utils\data_utils.py", line 206, in get_batch_data
    img_idx, img, y_true_13, y_true_26, y_true_52 = parse_data(line, class_num, img_size, anchors, mode)

  File "E:\net\new\YOLOv3_TensorFlow-master\utils\data_utils.py", line 124, in parse_data
    boxes = np.concatenate((boxes, np.full(shape=(boxes.shape[0], 1), fill_value=1., dtype=np.float32)), axis=-1)

ValueError: all the input arrays must have same number of dimensions


	 [[Node: PyFunc = PyFunc[Tin=[DT_STRING, DT_INT32, DT_INT32, DT_FLOAT, DT_STRING, DT_BOOL, DT_BOOL], Tout=[DT_INT64, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], token="pyfunc_0"](arg0, PyFunc/input_1, PyFunc/input_2, PyFunc/input_3, PyFunc/input_4, PyFunc/input_5, PyFunc/input_5)]]
	 [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[<unknown>, <unknown>, <unknown>, <unknown>, <unknown>], output_types=[DT_INT64, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](Iterator)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:/net/new/YOLOv3_TensorFlow-master/train.py", line 134, in <module>
    feed_dict={is_training: True})
  File "D:\anacconda\lib\site-packages\tensorflow\python\client\session.py", line 877, in run
    run_metadata_ptr)
  File "D:\anacconda\lib\site-packages\tensorflow\python\client\session.py", line 1100, in _run
    feed_dict_tensor, options, run_metadata)
  File "D:\anacconda\lib\site-packages\tensorflow\python\client\session.py", line 1272, in _do_run
    run_metadata)
  File "D:\anacconda\lib\site-packages\tensorflow\python\client\session.py", line 1291, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: ValueError: all the input arrays must have same number of dimensions
Traceback (most recent call last):

  File "D:\anacconda\lib\site-packages\tensorflow\python\ops\script_ops.py", line 206, in __call__
    ret = func(*args)

  File "E:\net\new\YOLOv3_TensorFlow-master\utils\data_utils.py", line 206, in get_batch_data
    img_idx, img, y_true_13, y_true_26, y_true_52 = parse_data(line, class_num, img_size, anchors, mode)

  File "E:\net\new\YOLOv3_TensorFlow-master\utils\data_utils.py", line 124, in parse_data
    boxes = np.concatenate((boxes, np.full(shape=(boxes.shape[0], 1), fill_value=1., dtype=np.float32)), axis=-1)

ValueError: all the input arrays must have same number of dimensions


	 [[Node: PyFunc = PyFunc[Tin=[DT_STRING, DT_INT32, DT_INT32, DT_FLOAT, DT_STRING, DT_BOOL, DT_BOOL], Tout=[DT_INT64, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], token="pyfunc_0"](arg0, PyFunc/input_1, PyFunc/input_2, PyFunc/input_3, PyFunc/input_4, PyFunc/input_5, PyFunc/input_5)]]
	 [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[<unknown>, <unknown>, <unknown>, <unknown>, <unknown>], output_types=[DT_INT64, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](Iterator)]]


Process finished with exit code 1
是有些图片不适合？

**Comment by wizyoung** [comment]
怀疑数据有损坏。那行出错的代码是把 shape 为 (n, 4) 和 (n, 1) 的 array 在最后一个维度 concat，得到 (n, 5). 怎么会维度不匹配呢

**Comment by eain3314** [comment]
但是我用这个数据集在之前的yolo v3中跑没什么错误啊，数据的格式不对？序号 路径 标签 坐标，是我的一张数据集上的框太多了吗？有70多个框的图

**Comment by wizyoung** [comment]
和框数目没关系，格式是对的。你自己 debug 下，中间加几个异常捕获看看哪里出问题了，我这里没什么问题

**Comment by eain3314** [comment]
我知道了 以为有一个这样的 595 E:\net\new\YOLOv3_TensorFlow-master\head\JPEGImages//PartA_00595.jpg 没有画框

**Comment by henbucuoshanghai** [comment]
图片里面一个bbox也没有的话，不能训练？
