### ISSUE TITLE
ValueError: all the input arrays must have same number of dimensions

### ISSUE THREAD

**Issue by henbucuoshanghai** [wizyoung/YOLOv3_TensorFlow#71]
File "/home/ubuntu/YOLOv3_TensorFlow/utils/data_utils.py", line 123, in parse_data
    boxes = np.concatenate((boxes, np.full(shape=(boxes.shape[0], 1), fill_value=1., dtype=np.float32)), axis=-1)

ValueError: all the input arrays must have same number of dimensions

**Comment by henbucuoshanghai** [comment]
[[{{node PyFunc}}]]
         [[node IteratorGetNext (defined at train.py:60) ]]
Exception ignored in: <function tqdm.__del__ at 0x7f06290ba510>
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/tqdm/_tqdm.py", line 931, in __del__
    self.close()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/tqdm/_tqdm.py", line 1133, in close
    self._decr_instances(self)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/tqdm/_tqdm.py", line 496, in _decr_instances
    cls.monitor.exit()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/tqdm/_monitor.py", line 52, in exit
    self.join()
  File "/home/ubuntu/anaconda3/lib/python3.7/threading.py", line 1029, in join
    raise RuntimeError("cannot join current thread")
RuntimeError: cannot join current thread

**Comment by chen3718** [comment]
@henbucuoshanghai  I met same error. how did u solve it?
