### ISSUE TITLE
ValueError: all the input arrays must have same number of dimensions

### ISSUE THREAD

**Issue by hehern** [wizyoung/YOLOv3_TensorFlow#95]
有几个疑问一起写在这里了，问下楼主。
１．必须用tensorflow gpu版本吗？我安装的tensorflow cpu版本，一样可以运行；
２．我训练自己的数据过程中，运行python3 train.py出现了，数据维度不匹配问题，请问是什么原因呢？train.txt是按照楼主的格式写的。
ubuntu@heruonan:~/people_counter/src/YOLOv3_TensorFlow$ python3 train.py

WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.

WARNING:tensorflow:From train.py:40: py_func (from tensorflow.python.ops.script_ops) is deprecated and will be removed in a future version.
Instructions for updating:
tf.py_func is deprecated in TF V2. Instead, use
    tf.py_function, which takes a python function which manipulates tf eager
    tensors instead of numpy arrays. It's easy to convert a tf eager tensor to
    an ndarray (just call tensor.numpy()) but having access to eager tensors
    means `tf.py_function`s can use accelerators such as GPUs as well as
    being differentiable using a gradient tape.
    
WARNING:tensorflow:From /home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/data/ops/iterator_ops.py:358: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
2019-06-17 20:53:52.730268: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-06-17 20:53:52.751410: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2904000000 Hz
2019-06-17 20:53:52.751622: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x1bfe840 executing computations on platform Host. Devices:
2019-06-17 20:53:52.751639: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
WARNING:tensorflow:From /home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/training/saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
INFO:tensorflow:Restoring parameters from ./data/darknet_weights/yolov3.ckpt

----------- start to train -----------

  0%|                                                                                                        | 0/6 [00:00<?, ?it/s]2019-06-17 20:54:08.719610: W tensorflow/core/framework/op_kernel.cc:1389] Invalid argument: ValueError: all the input arrays must have same number of dimensions
Traceback (most recent call last):

  File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 207, in __call__
    ret = func(*args)

  File "/home/ubuntu/people_counter/src/YOLOv3_TensorFlow/utils/data_utils.py", line 205, in get_batch_data
    img_idx, img, y_true_13, y_true_26, y_true_52 = parse_data(line, class_num, img_size, anchors, mode)

  File "/home/ubuntu/people_counter/src/YOLOv3_TensorFlow/utils/data_utils.py", line 124, in parse_data
    boxes = np.concatenate((boxes, np.full(shape=(boxes.shape[0], 1), fill_value=1., dtype=np.float32)), axis=-1)

ValueError: all the input arrays must have same number of dimensions

2019-06-17 20:54:08.730825: W tensorflow/core/framework/op_kernel.cc:1389] Invalid argument: ValueError: all the input arrays must have same number of dimensions
Traceback (most recent call last):

  File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 207, in __call__
    ret = func(*args)

  File "/home/ubuntu/people_counter/src/YOLOv3_TensorFlow/utils/data_utils.py", line 205, in get_batch_data
    img_idx, img, y_true_13, y_true_26, y_true_52 = parse_data(line, class_num, img_size, anchors, mode)

  File "/home/ubuntu/people_counter/src/YOLOv3_TensorFlow/utils/data_utils.py", line 124, in parse_data
    boxes = np.concatenate((boxes, np.full(shape=(boxes.shape[0], 1), fill_value=1., dtype=np.float32)), axis=-1)

ValueError: all the input arrays must have same number of dimensions

2019-06-17 20:54:08.731256: W tensorflow/core/framework/op_kernel.cc:1389] Invalid argument: ValueError: all the input arrays must have same number of dimensions
Traceback (most recent call last):

  File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 207, in __call__
    ret = func(*args)

  File "/home/ubuntu/people_counter/src/YOLOv3_TensorFlow/utils/data_utils.py", line 205, in get_batch_data
    img_idx, img, y_true_13, y_true_26, y_true_52 = parse_data(line, class_num, img_size, anchors, mode)

  File "/home/ubuntu/people_counter/src/YOLOv3_TensorFlow/utils/data_utils.py", line 124, in parse_data
    boxes = np.concatenate((boxes, np.full(shape=(boxes.shape[0], 1), fill_value=1., dtype=np.float32)), axis=-1)

ValueError: all the input arrays must have same number of dimensions

2019-06-17 20:54:08.800194: W tensorflow/core/framework/op_kernel.cc:1389] Invalid argument: ValueError: all the input arrays must have same number of dimensions
Traceback (most recent call last):

  File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 207, in __call__
    ret = func(*args)

  File "/home/ubuntu/people_counter/src/YOLOv3_TensorFlow/utils/data_utils.py", line 205, in get_batch_data
    img_idx, img, y_true_13, y_true_26, y_true_52 = parse_data(line, class_num, img_size, anchors, mode)

  File "/home/ubuntu/people_counter/src/YOLOv3_TensorFlow/utils/data_utils.py", line 124, in parse_data
    boxes = np.concatenate((boxes, np.full(shape=(boxes.shape[0], 1), fill_value=1., dtype=np.float32)), axis=-1)

ValueError: all the input arrays must have same number of dimensions

2019-06-17 20:54:08.846806: W tensorflow/core/framework/op_kernel.cc:1389] Invalid argument: ValueError: all the input arrays must have same number of dimensions
Traceback (most recent call last):

  File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 207, in __call__
    ret = func(*args)

  File "/home/ubuntu/people_counter/src/YOLOv3_TensorFlow/utils/data_utils.py", line 205, in get_batch_data
    img_idx, img, y_true_13, y_true_26, y_true_52 = parse_data(line, class_num, img_size, anchors, mode)

  File "/home/ubuntu/people_counter/src/YOLOv3_TensorFlow/utils/data_utils.py", line 124, in parse_data
    boxes = np.concatenate((boxes, np.full(shape=(boxes.shape[0], 1), fill_value=1., dtype=np.float32)), axis=-1)

ValueError: all the input arrays must have same number of dimensions

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: ValueError: all the input arrays must have same number of dimensions
Traceback (most recent call last):

  File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 207, in __call__
    ret = func(*args)

  File "/home/ubuntu/people_counter/src/YOLOv3_TensorFlow/utils/data_utils.py", line 205, in get_batch_data
    img_idx, img, y_true_13, y_true_26, y_true_52 = parse_data(line, class_num, img_size, anchors, mode)

  File "/home/ubuntu/people_counter/src/YOLOv3_TensorFlow/utils/data_utils.py", line 124, in parse_data
    boxes = np.concatenate((boxes, np.full(shape=(boxes.shape[0], 1), fill_value=1., dtype=np.float32)), axis=-1)

ValueError: all the input arrays must have same number of dimensions

	 [[{{node PyFunc}}]]
	 [[{{node IteratorGetNext}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 134, in <module>
    feed_dict={is_training: True})
  File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: ValueError: all the input arrays must have same number of dimensions
Traceback (most recent call last):

  File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 207, in __call__
    ret = func(*args)

  File "/home/ubuntu/people_counter/src/YOLOv3_TensorFlow/utils/data_utils.py", line 205, in get_batch_data
    img_idx, img, y_true_13, y_true_26, y_true_52 = parse_data(line, class_num, img_size, anchors, mode)

  File "/home/ubuntu/people_counter/src/YOLOv3_TensorFlow/utils/data_utils.py", line 124, in parse_data
    boxes = np.concatenate((boxes, np.full(shape=(boxes.shape[0], 1), fill_value=1., dtype=np.float32)), axis=-1)

ValueError: all the input arrays must have same number of dimensions

	 [[{{node PyFunc}}]]
	 [[node IteratorGetNext (defined at train.py:60) ]]

**Comment by PraveenJP** [comment]
@hehern Hi, Did you resolve the issue?

**Comment by hehern** [comment]
> @hehern Hi, Did you resolve the issue?
yes,maybe  it's because each image must have annotation information. If there is annotation information no the image, you should not  write it in the train.txt.

**Comment by hehern** [comment]
> @hehern Hi, Did you resolve the issue?

**Comment by wizyoung** [comment]
@hehern The error information of tf.data is kind of confusing. I plan to add more exceptions hints in the preprocess script.

**Comment by PraveenJP** [comment]
@hehern Ok Thanku. :)
